POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name":"Cosmo",
    "email":"cosmo@gmail.com",
    "password":"cosmo"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"cosmo@gmail.com",
    "password":"cosmo"
}

###
GET http://localhost:5000/api/users
Authorization: Bearer [put your token here]

###
GET http://localhost:5000/api/auth/refresh_token

### 
DELETE http://localhost:5000/api/auth/refresh_token
